#ifndef _INFRA_CONFIG_H_
#define _INFRA_CONFIG_H_

#define PLATFORM_HAS_MBEDTLS
#define PLATFORM_HAS_STDINT
#define PLATFORM_HAS_DYNMEM
#define INFRA_STRING
#define INFRA_NET
#define INFRA_LIST
#define INFRA_LOG_NETWORK_PAYLOAD
#define INFRA_LOG
#define INFRA_TIMER
#define INFRA_CJSON
#define INFRA_SHA256
#define INFRA_REPORT
#define INFRA_COMPAT
#define DEV_SIGN
#define MQTT_COMM_ENABLED
#define MQTT_DEFAULT_IMPL
#define MQTT_DIRECT
#define MQTT_AUTO_SUBSCRIBE
#define LOG_REPORT_TO_CLOUD
#define DEVICE_MODEL_ENABLED
#define SUPPORT_TLS

#endif
