#ifndef ASM_INCLUDES_H
#define ASM_INCLUDES_H


#include "audio.h"
#include "adc_api.h"
#include "cache.h"
#include "cpu.h"
#include "dma.h"
#include "debug.h"
#include "gpio.h"
#include "hwi.h"
#include "iic.h"
#include "irq.h"
#include "lock.h"
#include "sdmmc.h"
#include "spiflash.h"
#include "startup.h"
#include "uart.h"
#include "imc.h"
#include "isc.h"
#include "rtc.h"
#include "clock.h"
#include "crc16.h"
#include "spi.h"
#include "imd.h"
#include "imr.h"
#include "image_enc.h"
#include "jpeg_codec.h"
#include "imb_driver.h"
#include "uvc_device.h"
#include "bus_device.h"
#include "video/video.h"
#include "pap.h"
#include "emi.h"
#include "power_interface.h"
#include "p33.h"
#include "pwm.h"
#include "pwm_led.h"
#include "wdt.h"
#include "jpeg_decoder.h"


#endif
